[program:fifo_listener]
command=/home/aimee/order_book_server/fifo_listener/target/release/fifo_listener
directory=/home/aimee/order_book_server/fifo_listener
autostart=false
autorestart=true
startretries=3
startsecs=2
stopsignal=TERM
stopwaitsecs=10
stdout_logfile=/home/aimee/hl_runtime/hl_book/fifo_listener.out.log
stderr_logfile=/home/aimee/hl_runtime/hl_book/fifo_listener.err.log
